version: 2

registries:
  testpypi:
    type: python-index
    url: https://test.pypi.org/simple
    replaces-base: true

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - testpypi
    insecure-external-code-execution: allow
